const actionTypes = {
  ADD_CACHED_CHARACTERS: "ADD_CACHED_CHARACTERS",
  FILTER_CHARACTERS: "FILTER_CHARACTERS",
  LOAD_CHARACTER: "LOAD_CHARACTER",
  LOAD_CHARACTERS: "LOAD_CHARACTERS",
  REFRESH_CHARACTERS: "REFRESH_CHARACTERS",
  SORT_CHARACTERS: "SORT_CHARACTERS",
};

export { actionTypes };
