const actionTypes = {
  LOAD_MOVIES: "LOAD_MOVIES",
  LOAD_DETAILS: "LOAD_DETAILS",
  LOAD_CHARACTER: "LOAD_CHARACTER",
  REFRESH_MOVIE_CHARACTERS: "REFRESH_MOVIE_CHARACTERS",
  ADD_CACHED_CHARACTERS: "ADD_CACHED_CHARACTERS",
  FETCH_CHARACTERS_COMPLETE: "FETCH_CHARACTERS_COMPLETE",
  SORT_CHARACTERS: "SORT_CHARACTERS",
  FILTER_CHARACTERS_BY_GENDER: "FILTER_CHARACTERS_BY_GENDER",
  LOAD_MOVIE_CHARACTERS: "LOAD_MOVIE_CHARACTERS"
};

export { actionTypes };
